### ISSUE TITLE
Unable to access Web server

### ISSUE THREAD

**Issue by MehrabD123** [DPHacks/picow-air#3]
The picow is confirmed connected to the Wi-Fi network as I can see it connected to the router, but when trying to connect to the IP address it does not load any web page, any idea what the issue could be?

**Comment by camerahacks** [comment]
A little late, but anyone having this issue can download the latest ```code.py``` and copy to the board. This is most likely to an issue of the board trying to connect to a MQTT server even when this feature was disabled.
